In [1]:
import pandas as pd
import numpy as np
weather_data = {
    'day' : ['1/5/2024','5/4/2025','6/2/2023','5/5/2028','7/10/2025','3/5/2029'],
    'temperature' : [32,35,28,24,27,41],
    'windspeed' : [6,8,7,2,1,5],
    'event' : ['rain','sunny','snow','snow','rain','sunny']
}

In [2]:
df = pd.DataFrame(weather_data)
print(df)

         day  temperature  windspeed  event
0   1/5/2024           32          6   rain
1   5/4/2025           35          8  sunny
2   6/2/2023           28          7   snow
3   5/5/2028           24          2   snow
4  7/10/2025           27          1   rain
5   3/5/2029           41          5  sunny

In [4]:
df.shape

(6, 4)

In [10]:
r,c = df.shape
r,c

(6, 4)

In [11]:
df.head()

         day  temperature  windspeed  event
0   1/5/2024           32          6   rain
1   5/4/2025           35          8  sunny
2   6/2/2023           28          7   snow
3   5/5/2028           24          2   snow
4  7/10/2025           27          1   rain

In [12]:
df.tail()

         day  temperature  windspeed  event
1   5/4/2025           35          8  sunny
2   6/2/2023           28          7   snow
3   5/5/2028           24          2   snow
4  7/10/2025           27          1   rain
5   3/5/2029           41          5  sunny

In [14]:
df.head(2)

        day  temperature  windspeed  event
0  1/5/2024           32          6   rain
1  5/4/2025           35          8  sunny

In [15]:
df.tail(3)

         day  temperature  windspeed  event
3   5/5/2028           24          2   snow
4  7/10/2025           27          1   rain
5   3/5/2029           41          5  sunny

In [22]:
df.loc[2:4]

         day  temperature  windspeed event
2   6/2/2023           28          7  snow
3   5/5/2028           24          2  snow
4  7/10/2025           27          1  rain

In [25]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [26]:
df['temperature'].max()

41

In [27]:
df['temperature'].mean()

31.166666666666668

In [28]:
df['temperature'].min()

24

In [30]:
df.describe()

       temperature  windspeed
count     6.000000   6.000000
mean     31.166667   4.833333
std       6.177918   2.786874
min      24.000000   1.000000
25%      27.250000   2.750000
50%      30.000000   5.500000
75%      34.250000   6.750000
max      41.000000   8.000000

In [32]:
df[df['temperature']>32]

        day  temperature  windspeed  event
1  5/4/2025           35          8  sunny
5  3/5/2029           41          5  sunny

In [34]:
df[df['temperature'] == df['temperature'].max()]

        day  temperature  windspeed  event
5  3/5/2029           41          5  sunny

In [37]:
df.loc[df['temperature'].idxmax(),'day']

'3/5/2029'

In [40]:
df[['day','windspeed','temperature']][df.temperature == df['temperature'].max()]

        day  windspeed  temperature
5  3/5/2029          5           41

In [46]:
df.set_index('event',inplace = True)
df

       level_0  index        day  temperature  windspeed
event
rain         0      0   1/5/2024           32          6
sunny        1      1   5/4/2025           35          8
snow         2      2   6/2/2023           28          7
snow         3      3   5/5/2028           24          2
rain         4      4  7/10/2025           27          1
sunny        5      5   3/5/2029           41          5

In [47]:
df.reset_index(inplace=True)
df

   event  level_0  index        day  temperature  windspeed
0   rain        0      0   1/5/2024           32          6
1  sunny        1      1   5/4/2025           35          8
2   snow        2      2   6/2/2023           28          7
3   snow        3      3   5/5/2028           24          2
4   rain        4      4  7/10/2025           27          1
5  sunny        5      5   3/5/2029           41          5