In [3]:
import pandas as pd 
maharstra_weather = pd.DataFrame({
    "city" : ["Mumbai","Pune","Nagpur"],
    "temprature" : [32,30,40],
    "humidity" : [60,70,80]
})
maharstra_weather

     city  temprature  humidity
0  Mumbai          32        60
1    Pune          30        70
2  Nagpur          40        80

In [6]:
gujrat_weather=pd.DataFrame({
"city":["Baroda","Godhra","Bharuch"],
"temprature":[32,40,30],
"humidity":[80,60,70]
})
gujrat_weather

      city  temprature  humidity
0   Baroda          32        80
1   Godhra          40        60
2  Bharuch          30        70

In [8]:
df = pd.concat([gujrat_weather,maharstra_weather])
df

      city  temprature  humidity
0   Baroda          32        80
1   Godhra          40        60
2  Bharuch          30        70
0   Mumbai          32        60
1     Pune          30        70
2   Nagpur          40        80

In [16]:
df = pd.concat([gujrat_weather,maharstra_weather],ignore_index=True)
df

      city  temprature  humidity
0   Baroda          32        80
1   Godhra          40        60
2  Bharuch          30        70
3   Mumbai          32        60
4     Pune          30        70
5   Nagpur          40        80

In [17]:
df = pd.concat([gujrat_weather,maharstra_weather],keys=["Gujarat","Maharastra"])
df

                 city  temprature  humidity
Gujarat    0   Baroda          32        80
           1   Godhra          40        60
           2  Bharuch          30        70
Maharastra 0   Mumbai          32        60
           1     Pune          30        70
           2   Nagpur          40        80

In [18]:
df.loc["Gujarat"]

      city  temprature  humidity
0   Baroda          32        80
1   Godhra          40        60
2  Bharuch          30        70

In [19]:
df.loc["Maharastra"]

     city  temprature  humidity
0  Mumbai          32        60
1    Pune          30        70
2  Nagpur          40        80

In [26]:
temp_df = pd.DataFrame({
    "City" : ["Mumbai","Delhi","Banglore"],
    "Temprature" : [32,45,30]
})
temp_df.index = [10,11,22]
temp_df

        City  Temprature
10    Mumbai          32
11     Delhi          45
22  Banglore          30

In [21]:
windspeed_df = pd.DataFrame({
    "City" : ["Delhi","Mumbai"],
    "WindSpeed" : [7,12]
})
windspeed_df

     City  WindSpeed
0   Delhi          7
1  Mumbai         12

In [27]:
g = pd.concat([temp_df,windspeed_df])
g.index=[0,1,2,1,0]
g

       City  Temprature  WindSpeed
0    Mumbai        32.0        NaN
1     Delhi        45.0        NaN
2  Banglore        30.0        NaN
1     Delhi         NaN        7.0
0    Mumbai         NaN       12.0