In [1]:
import pandas as pd 
df1 = pd.DataFrame({
    "city" : ["new york","chicago","orland"],
    "temp" : [32,14,20]
})
df1

       city  temp
0  new york    32
1   chicago    14
2    orland    20

In [2]:
df2 = pd.DataFrame({
    "city" : ["chicago","new york","orland"],
    "humidity" : [65,68,75]
})
df2

       city  humidity
0   chicago        65
1  new york        68
2    orland        75

In [3]:
df3 = pd.merge(df1,df2,on="city")
df3

       city  temp  humidity
0  new york    32        68
1   chicago    14        65
2    orland    20        75

In [4]:
df1 = pd.DataFrame({
    "city" : ["new york","chicago","orland","baltimore"],
    "temp" : [32,14,20,38]
})
df1

        city  temp
0   new york    32
1    chicago    14
2     orland    20
3  baltimore    38

In [5]:
df2 = pd.DataFrame({
    "city" : ["chicago","new york","san diego"],
    "humidity" : [65,68,75]
})
df2

        city  humidity
0    chicago        65
1   new york        68
2  san diego        75

In [7]:
df3 = pd.merge(df1,df2,on="city",how="outer")
df3

        city  temp  humidity
0  baltimore  38.0       NaN
1    chicago  14.0      65.0
2   new york  32.0      68.0
3     orland  20.0       NaN
4  san diego   NaN      75.0

In [8]:
df3 = pd.merge(df1,df2,on="city",how="inner")
df3

       city  temp  humidity
0  new york    32        68
1   chicago    14        65

In [11]:
df3 = pd.merge(df1,df2,on="city",how="left")
df3

        city  temp  humidity
0   new york    32      68.0
1    chicago    14      65.0
2     orland    20       NaN
3  baltimore    38       NaN

In [12]:
df3 = pd.merge(df1,df2,on="city",how="right")
df3

        city  temp  humidity
0    chicago  14.0        65
1   new york  32.0        68
2  san diego   NaN        75

In [14]:
df3 = pd.merge(df1,df2,on="city",how="outer",indicator=True)
df3

        city  temp  humidity      _merge
0  baltimore  38.0       NaN   left_only
1    chicago  14.0      65.0        both
2   new york  32.0      68.0        both
3     orland  20.0       NaN   left_only
4  san diego   NaN      75.0  right_only