In [5]:
import pandas as pd
import numpy as np

In [6]:
import pandas as pd
import numpy as np
df1 = pd.read_csv("Dataset//weather1.csv")
df2 = pd.read_csv("Dataset//weather2.csv")
df1

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/2/2017  new york           66        58
2  5/3/2017  new york           68        60
3  5/1/2017    mumbai           75        80
4  5/2/2017    mumbai           78        83
5  5/3/2017    mumbai           82        85
6  5/1/2017   beijing           80        26
7  5/2/2017   beijing           77        30
8  5/3/2017   beijing           79        35

In [7]:
df2

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/1/2017  new york           61        54
2  5/2/2017  new york           70        60
3  5/2/2017  new york           72        62
4  5/1/2017    mumbai           75        80
5  5/1/2017    mumbai           78        83
6  5/2/2017    mumbai           82        85
7  5/2/2017    mumbai           80        26

In [12]:
# It is used for displaying data in a particular format
df1.pivot(index="city",columns="date")

         temperature                   humidity
date        5/1/2017 5/2/2017 5/3/2017 5/1/2017 5/2/2017 5/3/2017
city
beijing           80       77       79       26       30       35
mumbai            75       78       82       80       83       85
new york          65       66       68       56       58       60

In [9]:
df1.pivot(index="date",columns="city")

         temperature                 humidity
city         beijing mumbai new york  beijing mumbai new york
date
5/1/2017          80     75       65       26     80       56
5/2/2017          77     78       66       30     83       58
5/3/2017          79     82       68       35     85       60

In [10]:
df1.pivot(index="date",columns="city",values="humidity")

city      beijing  mumbai  new york
date
5/1/2017       26      80        56
5/2/2017       30      83        58
5/3/2017       35      85        60

In [11]:
df1.pivot(index="date",columns="city",values="temperature")

city      beijing  mumbai  new york
date
5/1/2017       80      75        65
5/2/2017       77      78        66
5/3/2017       79      82        68

In [14]:
df2.pivot_table(index="city",columns="date",aggfunc="sum")

         humidity          temperature
date     5/1/2017 5/2/2017    5/1/2017 5/2/2017
city
mumbai        163      111         153      162
new york      110      122         126      142