In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("Dataset//FoodOrderDetails.csv")
df

     1/1/2017   Burger    10  1000 10000
0    1/2/2017   Nofood     5  n.a.  5000
1    1/3/2017   Franky    11   500  5500
2    1/4/2018   Nofood     0  n.a.   800
3    5/9/2020   Samosa    20    15     0
4     missing  Kachori     0    10    30
5  11/12/2022     Dosa     5  n.a.     0
6   10/9/2023    Momos    10    10   100
7     missing   Nofood  n.a.    30  n.a.
8  15/12/2024  Paratha   100    30  3000

In [4]:
df = pd.read_csv("Dataset//FoodOrderDetails.csv",header=None)
df

            0        1     2     3      4
0    1/1/2017   Burger    10  1000  10000
1    1/2/2017   Nofood     5  n.a.   5000
2    1/3/2017   Franky    11   500   5500
3    1/4/2018   Nofood     0  n.a.    800
4    5/9/2020   Samosa    20    15      0
5     missing  Kachori     0    10     30
6  11/12/2022     Dosa     5  n.a.      0
7   10/9/2023    Momos    10    10    100
8     missing   Nofood  n.a.    30   n.a.
9  15/12/2024  Paratha   100    30   3000

In [5]:
df = pd.read_csv("Dataset//FoodOrderDetails.csv",header=None)
df.columns=[["OrdDate","Name","Qty","Price","Total"]]
df

      OrdDate     Name   Qty Price  Total
0    1/1/2017   Burger    10  1000  10000
1    1/2/2017   Nofood     5  n.a.   5000
2    1/3/2017   Franky    11   500   5500
3    1/4/2018   Nofood     0  n.a.    800
4    5/9/2020   Samosa    20    15      0
5     missing  Kachori     0    10     30
6  11/12/2022     Dosa     5  n.a.      0
7   10/9/2023    Momos    10    10    100
8     missing   Nofood  n.a.    30   n.a.
9  15/12/2024  Paratha   100    30   3000

In [6]:
df.replace([0,"n.a."],np.nan,inplace=True)
df

      OrdDate     Name  Qty Price  Total
0    1/1/2017   Burger   10  1000  10000
1    1/2/2017   Nofood    5   NaN   5000
2    1/3/2017   Franky   11   500   5500
3    1/4/2018   Nofood    0   NaN    800
4    5/9/2020   Samosa   20    15      0
5     missing  Kachori    0    10     30
6  11/12/2022     Dosa    5   NaN      0
7   10/9/2023    Momos   10    10    100
8     missing   Nofood  NaN    30    NaN
9  15/12/2024  Paratha  100    30   3000

In [7]:
# df.replace(["missing"],"##/##/####",inplace=True)
# df
df = pd.read_csv("Dataset\\FoodOrderDetails.csv", names=["OrdDate","Name","Qty","Price","Total"],na_values=["0","n.a."])
df

      OrdDate     Name    Qty   Price    Total
0    1/1/2017   Burger   10.0  1000.0  10000.0
1    1/2/2017   Nofood    5.0     NaN   5000.0
2    1/3/2017   Franky   11.0   500.0   5500.0
3    1/4/2018   Nofood    NaN     NaN    800.0
4    5/9/2020   Samosa   20.0    15.0      NaN
5     missing  Kachori    NaN    10.0     30.0
6  11/12/2022     Dosa    5.0     NaN      NaN
7   10/9/2023    Momos   10.0    10.0    100.0
8     missing   Nofood    NaN    30.0      NaN
9  15/12/2024  Paratha  100.0    30.0   3000.0

In [8]:
# df.replace(["Nofood"],"Panipuri",inplace=True)
# df
df.replace(["missing"],"##/##/####",inplace=True)
df

      OrdDate     Name    Qty   Price    Total
0    1/1/2017   Burger   10.0  1000.0  10000.0
1    1/2/2017   Nofood    5.0     NaN   5000.0
2    1/3/2017   Franky   11.0   500.0   5500.0
3    1/4/2018   Nofood    NaN     NaN    800.0
4    5/9/2020   Samosa   20.0    15.0      NaN
5  ##/##/####  Kachori    NaN    10.0     30.0
6  11/12/2022     Dosa    5.0     NaN      NaN
7   10/9/2023    Momos   10.0    10.0    100.0
8  ##/##/####   Nofood    NaN    30.0      NaN
9  15/12/2024  Paratha  100.0    30.0   3000.0

In [9]:
df[['Qty', 'Price','Total']] = df[['Qty', 'Price','Total']].fillna(value=0)
df

      OrdDate     Name    Qty   Price    Total
0    1/1/2017   Burger   10.0  1000.0  10000.0
1    1/2/2017   Nofood    5.0     0.0   5000.0
2    1/3/2017   Franky   11.0   500.0   5500.0
3    1/4/2018   Nofood    0.0     0.0    800.0
4    5/9/2020   Samosa   20.0    15.0      0.0
5  ##/##/####  Kachori    0.0    10.0     30.0
6  11/12/2022     Dosa    5.0     0.0      0.0
7   10/9/2023    Momos   10.0    10.0    100.0
8  ##/##/####   Nofood    0.0    30.0      0.0
9  15/12/2024  Paratha  100.0    30.0   3000.0

In [10]:
df.loc[df['Price'] == 0, 'Total'] = 0
df

      OrdDate     Name    Qty   Price    Total
0    1/1/2017   Burger   10.0  1000.0  10000.0
1    1/2/2017   Nofood    5.0     0.0      0.0
2    1/3/2017   Franky   11.0   500.0   5500.0
3    1/4/2018   Nofood    0.0     0.0      0.0
4    5/9/2020   Samosa   20.0    15.0      0.0
5  ##/##/####  Kachori    0.0    10.0     30.0
6  11/12/2022     Dosa    5.0     0.0      0.0
7   10/9/2023    Momos   10.0    10.0    100.0
8  ##/##/####   Nofood    0.0    30.0      0.0
9  15/12/2024  Paratha  100.0    30.0   3000.0

In [11]:
df.loc[df['Qty'] == 0, 'Total'] = 0
df

      OrdDate     Name    Qty   Price    Total
0    1/1/2017   Burger   10.0  1000.0  10000.0
1    1/2/2017   Nofood    5.0     0.0      0.0
2    1/3/2017   Franky   11.0   500.0   5500.0
3    1/4/2018   Nofood    0.0     0.0      0.0
4    5/9/2020   Samosa   20.0    15.0      0.0
5  ##/##/####  Kachori    0.0    10.0      0.0
6  11/12/2022     Dosa    5.0     0.0      0.0
7   10/9/2023    Momos   10.0    10.0    100.0
8  ##/##/####   Nofood    0.0    30.0      0.0
9  15/12/2024  Paratha  100.0    30.0   3000.0

In [12]:
df[df['Qty'] == 0]

      OrdDate     Name  Qty  Price  Total
3    1/4/2018   Nofood  0.0    0.0    0.0
5  ##/##/####  Kachori  0.0   10.0    0.0
8  ##/##/####   Nofood  0.0   30.0    0.0

In [13]:
df[df['Price'] == 0]

      OrdDate    Name  Qty  Price  Total
1    1/2/2017  Nofood  5.0    0.0    0.0
3    1/4/2018  Nofood  0.0    0.0    0.0
6  11/12/2022    Dosa  5.0    0.0    0.0

In [14]:
df[df['Total'] > 0]

      OrdDate     Name    Qty   Price    Total
0    1/1/2017   Burger   10.0  1000.0  10000.0
2    1/3/2017   Franky   11.0   500.0   5500.0
7   10/9/2023    Momos   10.0    10.0    100.0
9  15/12/2024  Paratha  100.0    30.0   3000.0

In [15]:
df[(df['Qty'] == 0) & (df['Price'] == 0) & (df['Total'] == 0)]

    OrdDate    Name  Qty  Price  Total
3  1/4/2018  Nofood  0.0    0.0    0.0

In [22]:
df_filtered = df[~((df['Qty'] == 0) | (df['Price'] == 0) | (df['Total'] == 0))]
df_filtered

      OrdDate     Name    Qty   Price    Total
0    1/1/2017   Burger   10.0  1000.0  10000.0
2    1/3/2017   Franky   11.0   500.0   5500.0
7   10/9/2023    Momos   10.0    10.0    100.0
9  15/12/2024  Paratha  100.0    30.0   3000.0

In [23]:
df_filtered.to_csv("Dataset//FoodOrderDetails1.csv", index=False)

In [24]:
import os
print(os.path.exists("Dataset//FoodOrderDetails1.csv"))

True

In [26]:
df1 = pd.read_csv("Dataset//FoodOrderDetails1.csv")
df1

      OrdDate     Name    Qty   Price    Total
0    1/1/2017   Burger   10.0  1000.0  10000.0
1    1/3/2017   Franky   11.0   500.0   5500.0
2   10/9/2023    Momos   10.0    10.0    100.0
3  15/12/2024  Paratha  100.0    30.0   3000.0