In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
files = os.listdir("dataset/mp")
print("=> TXT Files")
for file in files:
    if file.endswith(".txt"):
        print(file)
print("=> CSV Files:")
for file in files:
    if file.endswith(".csv"):
        print(file)
print("=> Folders")
for file in files:
    if os.path.isdir(os.path.join("dataset/mp", file)):
        print(file)

=> TXT Files
=> CSV Files:
all_sales.csv
sales1.csv
sales2.csv
sales3.csv
sales4.csv
sales5.csv
sales6.csv
=> Folders
.ipynb_checkpoints

In [3]:
folder_count = "Dataset//MP"
file_count = sum(
    os.path.isfile(os.path.join(folder_count, f)) 
    for f in os.listdir(folder_count)
)
print("Total number of files:", file_count)

Total number of files: 7

In [4]:
# mypath="dataset//mp"
# files = os.listdir("dataset//mp")
# for file in files:
#     if file.endswith(".csv") or file.endswith(".txt"):
#         print(file)
#     else:
#         os.rmdir(mypath + "/" + file)

In [5]:
files = os.listdir("dataset/mp")
for file in files:
    if file.endswith(".txt"):
        path = os.path.join("dataset/mp", file)
        os.remove(path)
        print(f"Deleted: {file}")

In [6]:
print("=> CSV Files:")
for file in files:
    if file.endswith(".csv"):
        print(file)

=> CSV Files:
all_sales.csv
sales1.csv
sales2.csv
sales3.csv
sales4.csv
sales5.csv
sales6.csv

In [7]:
if os.path.exists("Dataset/MP/all_sales.csv"):
  os.remove("Dataset/MP/all_sales.csv")
else:
  print("The file does not exist")

In [8]:
folder = "dataset/mp"
csv_files = [f for f in os.listdir(folder) if f.endswith(".csv")]
dataframes = []
for file in csv_files:
    path = os.path.join(folder, file)
    df = pd.read_csv(path)
    df["source_file"] = file  
    dataframes.append(df)
all_sales = pd.concat(dataframes, ignore_index=True)
print("all_sales DataFrame:")
print(all_sales)

all_sales DataFrame:
      Order ID                     Product Quantity Ordered Price Each  \
0       236670            Wired Headphones                2      11.99
1       236671  Bose SoundSport Headphones                1      99.99
2       236672                      iPhone                1      700.0
3       236673       AA Batteries (4-pack)                2       3.84
4       236674       AA Batteries (4-pack)                2       3.84
...        ...                         ...              ...        ...
66061   236665            Wired Headphones                1      11.99
66062   236666                20in Monitor                1     109.99
66063   236667      AAA Batteries (4-pack)                1       2.99
66064   236668            Wired Headphones                1      11.99
66065   236669      AAA Batteries (4-pack)                1       2.99

           Order Date                      Purchase Address source_file
0      08/31/19 22:21      359 Spruce St, Seattle, WA 98101  sales1.csv
1      08/15/19 15:11        492 Ridge St, Dallas, TX 75001  sales1.csv
2      08/06/19 14:40        149 7th St, Portland, OR 97035  sales1.csv
3      08/29/19 20:59     631 2nd St, Los Angeles, CA 90001  sales1.csv
4      08/15/19 19:53  736 14th St, New York City, NY 10001  sales1.csv
...               ...                                   ...         ...
66061  07/20/19 16:16      694 Meadow St, Atlanta, GA 30301  sales6.csv
66062  07/31/19 20:11  866 14th St, San Francisco, CA 94016  sales6.csv
66063  07/17/19 22:29       249 Cherry St, Dallas, TX 75001  sales6.csv
66064  07/30/19 19:28       727 Wilson St, Austin, TX 73301  sales6.csv
66065  07/10/19 01:50   743 9th St, New York City, NY 10001  sales6.csv

[66066 rows x 7 columns]

In [9]:
all_sales

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,source_file
0,236670,Wired Headphones,2,11.99,08/31/19 22:21,"359 Spruce St, Seattle, WA 98101",sales1.csv
1,236671,Bose SoundSport Headphones,1,99.99,08/15/19 15:11,"492 Ridge St, Dallas, TX 75001",sales1.csv
2,236672,iPhone,1,700.0,08/06/19 14:40,"149 7th St, Portland, OR 97035",sales1.csv
3,236673,AA Batteries (4-pack),2,3.84,08/29/19 20:59,"631 2nd St, Los Angeles, CA 90001",sales1.csv
4,236674,AA Batteries (4-pack),2,3.84,08/15/19 19:53,"736 14th St, New York City, NY 10001",sales1.csv
...,...,...,...,...,...,...,...
66061,236665,Wired Headphones,1,11.99,07/20/19 16:16,"694 Meadow St, Atlanta, GA 30301",sales6.csv
66062,236666,20in Monitor,1,109.99,07/31/19 20:11,"866 14th St, San Francisco, CA 94016",sales6.csv
66063,236667,AAA Batteries (4-pack),1,2.99,07/17/19 22:29,"249 Cherry St, Dallas, TX 75001",sales6.csv
66064,236668,Wired Headphones,1,11.99,07/30/19 19:28,"727 Wilson St, Austin, TX 73301",sales6.csv
66065,236669,AAA Batteries (4-pack),1,2.99,07/10/19 01:50,"743 9th St, New York City, NY 10001",sales6.csv

In [10]:
all_sales.to_csv("dataset/mp/all_sales.csv", index=False)
print("Saved as: all_sales.csv")

Saved as: all_sales.csv

In [11]:
print(all_sales["Order Date"])

0        08/31/19 22:21
1        08/15/19 15:11
2        08/06/19 14:40
3        08/29/19 20:59
4        08/15/19 19:53
              ...
66061    07/20/19 16:16
66062    07/31/19 20:11
66063    07/17/19 22:29
66064    07/30/19 19:28
66065    07/10/19 01:50
Name: Order Date, Length: 66066, dtype: object

In [12]:
all_sales["Order Date"].str[:2]

0        08
1        08
2        08
3        08
4        08
         ..
66061    07
66062    07
66063    07
66064    07
66065    07
Name: Order Date, Length: 66066, dtype: object

In [13]:
# Find month having highest sales
all_sales["Month"]= all_sales["Order Date"].str[:2]
all_sales

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,source_file,Month
0,236670,Wired Headphones,2,11.99,08/31/19 22:21,"359 Spruce St, Seattle, WA 98101",sales1.csv,08
1,236671,Bose SoundSport Headphones,1,99.99,08/15/19 15:11,"492 Ridge St, Dallas, TX 75001",sales1.csv,08
2,236672,iPhone,1,700.0,08/06/19 14:40,"149 7th St, Portland, OR 97035",sales1.csv,08
3,236673,AA Batteries (4-pack),2,3.84,08/29/19 20:59,"631 2nd St, Los Angeles, CA 90001",sales1.csv,08
4,236674,AA Batteries (4-pack),2,3.84,08/15/19 19:53,"736 14th St, New York City, NY 10001",sales1.csv,08
...,...,...,...,...,...,...,...,...
66061,236665,Wired Headphones,1,11.99,07/20/19 16:16,"694 Meadow St, Atlanta, GA 30301",sales6.csv,07
66062,236666,20in Monitor,1,109.99,07/31/19 20:11,"866 14th St, San Francisco, CA 94016",sales6.csv,07
66063,236667,AAA Batteries (4-pack),1,2.99,07/17/19 22:29,"249 Cherry St, Dallas, TX 75001",sales6.csv,07
66064,236668,Wired Headphones,1,11.99,07/30/19 19:28,"727 Wilson St, Austin, TX 73301",sales6.csv,07
66065,236669,AAA Batteries (4-pack),1,2.99,07/10/19 01:50,"743 9th St, New York City, NY 10001",sales6.csv,07

In [14]:
all_sales.to_csv("dataset/mp/all_sales.csv", index=False)
print("Saved as: all_sales.csv")

Saved as: all_sales.csv

In [15]:
# all_sales['Month'] = all_sales['Month'].astype("int32")
# all_sales

Solving above error

In [16]:
# filtered_rows = all_sales[all_sales["Month"].astype(str).str.contains("Or", case=False)]
# filtered_rows

In [17]:
or_df = all_sales[all_sales['Order Date'].str[0:2]=='Or']
or_df

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,source_file,Month
211,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,sales1.csv,Or
243,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,sales1.csv,Or
1291,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,sales1.csv,Or
1412,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,sales1.csv,Or
1427,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,sales1.csv,Or
...,...,...,...,...,...,...,...,...
62004,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,sales6.csv,Or
63684,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,sales6.csv,Or
63732,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,sales6.csv,Or
64376,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,sales6.csv,Or
65603,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,sales6.csv,Or

In [18]:
all_sales = all_sales[all_sales['Order Date'].str[0:2]!='Or']
all_sales

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,source_file,Month
0,236670,Wired Headphones,2,11.99,08/31/19 22:21,"359 Spruce St, Seattle, WA 98101",sales1.csv,08
1,236671,Bose SoundSport Headphones,1,99.99,08/15/19 15:11,"492 Ridge St, Dallas, TX 75001",sales1.csv,08
2,236672,iPhone,1,700.0,08/06/19 14:40,"149 7th St, Portland, OR 97035",sales1.csv,08
3,236673,AA Batteries (4-pack),2,3.84,08/29/19 20:59,"631 2nd St, Los Angeles, CA 90001",sales1.csv,08
4,236674,AA Batteries (4-pack),2,3.84,08/15/19 19:53,"736 14th St, New York City, NY 10001",sales1.csv,08
...,...,...,...,...,...,...,...,...
66061,236665,Wired Headphones,1,11.99,07/20/19 16:16,"694 Meadow St, Atlanta, GA 30301",sales6.csv,07
66062,236666,20in Monitor,1,109.99,07/31/19 20:11,"866 14th St, San Francisco, CA 94016",sales6.csv,07
66063,236667,AAA Batteries (4-pack),1,2.99,07/17/19 22:29,"249 Cherry St, Dallas, TX 75001",sales6.csv,07
66064,236668,Wired Headphones,1,11.99,07/30/19 19:28,"727 Wilson St, Austin, TX 73301",sales6.csv,07
66065,236669,AAA Batteries (4-pack),1,2.99,07/10/19 01:50,"743 9th St, New York City, NY 10001",sales6.csv,07

In [19]:
or_df = all_sales[all_sales['Order Date'].str[0:2]=='Or']
or_df

Empty DataFrame
Columns: [Order ID, Product, Quantity Ordered, Price Each, Order Date, Purchase Address, source_file, Month]
Index: []

In [20]:
nan_rows = all_sales[all_sales.isna().any(axis=1)]
nan_rows

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,source_file,Month
312,NaN,NaN,NaN,NaN,NaN,NaN,sales1.csv,NaN
1222,NaN,NaN,NaN,NaN,NaN,NaN,sales1.csv,NaN
2648,NaN,NaN,NaN,NaN,NaN,NaN,sales1.csv,NaN
2685,NaN,NaN,NaN,NaN,NaN,NaN,sales1.csv,NaN
3119,NaN,NaN,NaN,NaN,NaN,NaN,sales1.csv,NaN
...,...,...,...,...,...,...,...,...
64731,NaN,NaN,NaN,NaN,NaN,NaN,sales6.csv,NaN
64866,NaN,NaN,NaN,NaN,NaN,NaN,sales6.csv,NaN
65728,NaN,NaN,NaN,NaN,NaN,NaN,sales6.csv,NaN
65936,NaN,NaN,NaN,NaN,NaN,NaN,sales6.csv,NaN
66026,NaN,NaN,NaN,NaN,NaN,NaN,sales6.csv,NaN

In [21]:
all_sales = all_sales.dropna(how='all')
all_sales

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,source_file,Month
0,236670,Wired Headphones,2,11.99,08/31/19 22:21,"359 Spruce St, Seattle, WA 98101",sales1.csv,08
1,236671,Bose SoundSport Headphones,1,99.99,08/15/19 15:11,"492 Ridge St, Dallas, TX 75001",sales1.csv,08
2,236672,iPhone,1,700.0,08/06/19 14:40,"149 7th St, Portland, OR 97035",sales1.csv,08
3,236673,AA Batteries (4-pack),2,3.84,08/29/19 20:59,"631 2nd St, Los Angeles, CA 90001",sales1.csv,08
4,236674,AA Batteries (4-pack),2,3.84,08/15/19 19:53,"736 14th St, New York City, NY 10001",sales1.csv,08
...,...,...,...,...,...,...,...,...
66061,236665,Wired Headphones,1,11.99,07/20/19 16:16,"694 Meadow St, Atlanta, GA 30301",sales6.csv,07
66062,236666,20in Monitor,1,109.99,07/31/19 20:11,"866 14th St, San Francisco, CA 94016",sales6.csv,07
66063,236667,AAA Batteries (4-pack),1,2.99,07/17/19 22:29,"249 Cherry St, Dallas, TX 75001",sales6.csv,07
66064,236668,Wired Headphones,1,11.99,07/30/19 19:28,"727 Wilson St, Austin, TX 73301",sales6.csv,07
66065,236669,AAA Batteries (4-pack),1,2.99,07/10/19 01:50,"743 9th St, New York City, NY 10001",sales6.csv,07

In [22]:
nan_rows = all_sales[all_sales.isna().any(axis=1)]
nan_rows

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,source_file,Month
312,NaN,NaN,NaN,NaN,NaN,NaN,sales1.csv,NaN
1222,NaN,NaN,NaN,NaN,NaN,NaN,sales1.csv,NaN
2648,NaN,NaN,NaN,NaN,NaN,NaN,sales1.csv,NaN
2685,NaN,NaN,NaN,NaN,NaN,NaN,sales1.csv,NaN
3119,NaN,NaN,NaN,NaN,NaN,NaN,sales1.csv,NaN
...,...,...,...,...,...,...,...,...
64731,NaN,NaN,NaN,NaN,NaN,NaN,sales6.csv,NaN
64866,NaN,NaN,NaN,NaN,NaN,NaN,sales6.csv,NaN
65728,NaN,NaN,NaN,NaN,NaN,NaN,sales6.csv,NaN
65936,NaN,NaN,NaN,NaN,NaN,NaN,sales6.csv,NaN
66026,NaN,NaN,NaN,NaN,NaN,NaN,sales6.csv,NaN

In [23]:
all_sales = all_sales.dropna()
all_sales

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,source_file,Month
0,236670,Wired Headphones,2,11.99,08/31/19 22:21,"359 Spruce St, Seattle, WA 98101",sales1.csv,08
1,236671,Bose SoundSport Headphones,1,99.99,08/15/19 15:11,"492 Ridge St, Dallas, TX 75001",sales1.csv,08
2,236672,iPhone,1,700.0,08/06/19 14:40,"149 7th St, Portland, OR 97035",sales1.csv,08
3,236673,AA Batteries (4-pack),2,3.84,08/29/19 20:59,"631 2nd St, Los Angeles, CA 90001",sales1.csv,08
4,236674,AA Batteries (4-pack),2,3.84,08/15/19 19:53,"736 14th St, New York City, NY 10001",sales1.csv,08
...,...,...,...,...,...,...,...,...
66061,236665,Wired Headphones,1,11.99,07/20/19 16:16,"694 Meadow St, Atlanta, GA 30301",sales6.csv,07
66062,236666,20in Monitor,1,109.99,07/31/19 20:11,"866 14th St, San Francisco, CA 94016",sales6.csv,07
66063,236667,AAA Batteries (4-pack),1,2.99,07/17/19 22:29,"249 Cherry St, Dallas, TX 75001",sales6.csv,07
66064,236668,Wired Headphones,1,11.99,07/30/19 19:28,"727 Wilson St, Austin, TX 73301",sales6.csv,07
66065,236669,AAA Batteries (4-pack),1,2.99,07/10/19 01:50,"743 9th St, New York City, NY 10001",sales6.csv,07

In [24]:
nan_rows = all_sales[all_sales.isna().any(axis=1)]
nan_rows

Empty DataFrame
Columns: [Order ID, Product, Quantity Ordered, Price Each, Order Date, Purchase Address, source_file, Month]
Index: []

In [25]:
all_sales['Month'] = all_sales['Month'].astype("int32")
all_sales.to_csv("Dataset/MP/all_sales.csv",index = False)
all_sales

C:\Users\Jaina\AppData\Local\Temp\ipykernel_8844\1156339002.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_sales['Month'] = all_sales['Month'].astype("int32")

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,source_file,Month
0,236670,Wired Headphones,2,11.99,08/31/19 22:21,"359 Spruce St, Seattle, WA 98101",sales1.csv,8
1,236671,Bose SoundSport Headphones,1,99.99,08/15/19 15:11,"492 Ridge St, Dallas, TX 75001",sales1.csv,8
2,236672,iPhone,1,700.0,08/06/19 14:40,"149 7th St, Portland, OR 97035",sales1.csv,8
3,236673,AA Batteries (4-pack),2,3.84,08/29/19 20:59,"631 2nd St, Los Angeles, CA 90001",sales1.csv,8
4,236674,AA Batteries (4-pack),2,3.84,08/15/19 19:53,"736 14th St, New York City, NY 10001",sales1.csv,8
...,...,...,...,...,...,...,...,...
66061,236665,Wired Headphones,1,11.99,07/20/19 16:16,"694 Meadow St, Atlanta, GA 30301",sales6.csv,7
66062,236666,20in Monitor,1,109.99,07/31/19 20:11,"866 14th St, San Francisco, CA 94016",sales6.csv,7
66063,236667,AAA Batteries (4-pack),1,2.99,07/17/19 22:29,"249 Cherry St, Dallas, TX 75001",sales6.csv,7
66064,236668,Wired Headphones,1,11.99,07/30/19 19:28,"727 Wilson St, Austin, TX 73301",sales6.csv,7
66065,236669,AAA Batteries (4-pack),1,2.99,07/10/19 01:50,"743 9th St, New York City, NY 10001",sales6.csv,7

In [26]:
mypath = "Dataset/MP/all_sales.csv"
all_sales = pd.read_csv(mypath)
all_sales

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,source_file,Month
0,236670,Wired Headphones,2,11.99,08/31/19 22:21,"359 Spruce St, Seattle, WA 98101",sales1.csv,8
1,236671,Bose SoundSport Headphones,1,99.99,08/15/19 15:11,"492 Ridge St, Dallas, TX 75001",sales1.csv,8
2,236672,iPhone,1,700.00,08/06/19 14:40,"149 7th St, Portland, OR 97035",sales1.csv,8
3,236673,AA Batteries (4-pack),2,3.84,08/29/19 20:59,"631 2nd St, Los Angeles, CA 90001",sales1.csv,8
4,236674,AA Batteries (4-pack),2,3.84,08/15/19 19:53,"736 14th St, New York City, NY 10001",sales1.csv,8
...,...,...,...,...,...,...,...,...
65753,236665,Wired Headphones,1,11.99,07/20/19 16:16,"694 Meadow St, Atlanta, GA 30301",sales6.csv,7
65754,236666,20in Monitor,1,109.99,07/31/19 20:11,"866 14th St, San Francisco, CA 94016",sales6.csv,7
65755,236667,AAA Batteries (4-pack),1,2.99,07/17/19 22:29,"249 Cherry St, Dallas, TX 75001",sales6.csv,7
65756,236668,Wired Headphones,1,11.99,07/30/19 19:28,"727 Wilson St, Austin, TX 73301",sales6.csv,7
65757,236669,AAA Batteries (4-pack),1,2.99,07/10/19 01:50,"743 9th St, New York City, NY 10001",sales6.csv,7

In [27]:
all_sales['Month']=all_sales['Month'].astype('int32')
all_sales

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,source_file,Month
0,236670,Wired Headphones,2,11.99,08/31/19 22:21,"359 Spruce St, Seattle, WA 98101",sales1.csv,8
1,236671,Bose SoundSport Headphones,1,99.99,08/15/19 15:11,"492 Ridge St, Dallas, TX 75001",sales1.csv,8
2,236672,iPhone,1,700.00,08/06/19 14:40,"149 7th St, Portland, OR 97035",sales1.csv,8
3,236673,AA Batteries (4-pack),2,3.84,08/29/19 20:59,"631 2nd St, Los Angeles, CA 90001",sales1.csv,8
4,236674,AA Batteries (4-pack),2,3.84,08/15/19 19:53,"736 14th St, New York City, NY 10001",sales1.csv,8
...,...,...,...,...,...,...,...,...
65753,236665,Wired Headphones,1,11.99,07/20/19 16:16,"694 Meadow St, Atlanta, GA 30301",sales6.csv,7
65754,236666,20in Monitor,1,109.99,07/31/19 20:11,"866 14th St, San Francisco, CA 94016",sales6.csv,7
65755,236667,AAA Batteries (4-pack),1,2.99,07/17/19 22:29,"249 Cherry St, Dallas, TX 75001",sales6.csv,7
65756,236668,Wired Headphones,1,11.99,07/30/19 19:28,"727 Wilson St, Austin, TX 73301",sales6.csv,7
65757,236669,AAA Batteries (4-pack),1,2.99,07/10/19 01:50,"743 9th St, New York City, NY 10001",sales6.csv,7

In [28]:
all_sales['Quantity Ordered']=all_sales['Quantity Ordered'].astype('int32')
all_sales

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,source_file,Month
0,236670,Wired Headphones,2,11.99,08/31/19 22:21,"359 Spruce St, Seattle, WA 98101",sales1.csv,8
1,236671,Bose SoundSport Headphones,1,99.99,08/15/19 15:11,"492 Ridge St, Dallas, TX 75001",sales1.csv,8
2,236672,iPhone,1,700.00,08/06/19 14:40,"149 7th St, Portland, OR 97035",sales1.csv,8
3,236673,AA Batteries (4-pack),2,3.84,08/29/19 20:59,"631 2nd St, Los Angeles, CA 90001",sales1.csv,8
4,236674,AA Batteries (4-pack),2,3.84,08/15/19 19:53,"736 14th St, New York City, NY 10001",sales1.csv,8
...,...,...,...,...,...,...,...,...
65753,236665,Wired Headphones,1,11.99,07/20/19 16:16,"694 Meadow St, Atlanta, GA 30301",sales6.csv,7
65754,236666,20in Monitor,1,109.99,07/31/19 20:11,"866 14th St, San Francisco, CA 94016",sales6.csv,7
65755,236667,AAA Batteries (4-pack),1,2.99,07/17/19 22:29,"249 Cherry St, Dallas, TX 75001",sales6.csv,7
65756,236668,Wired Headphones,1,11.99,07/30/19 19:28,"727 Wilson St, Austin, TX 73301",sales6.csv,7
65757,236669,AAA Batteries (4-pack),1,2.99,07/10/19 01:50,"743 9th St, New York City, NY 10001",sales6.csv,7

In [29]:
all_sales['Price Each']=all_sales['Price Each'].astype('float32')
all_sales

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,source_file,Month
0,236670,Wired Headphones,2,11.990000,08/31/19 22:21,"359 Spruce St, Seattle, WA 98101",sales1.csv,8
1,236671,Bose SoundSport Headphones,1,99.989998,08/15/19 15:11,"492 Ridge St, Dallas, TX 75001",sales1.csv,8
2,236672,iPhone,1,700.000000,08/06/19 14:40,"149 7th St, Portland, OR 97035",sales1.csv,8
3,236673,AA Batteries (4-pack),2,3.840000,08/29/19 20:59,"631 2nd St, Los Angeles, CA 90001",sales1.csv,8
4,236674,AA Batteries (4-pack),2,3.840000,08/15/19 19:53,"736 14th St, New York City, NY 10001",sales1.csv,8
...,...,...,...,...,...,...,...,...
65753,236665,Wired Headphones,1,11.990000,07/20/19 16:16,"694 Meadow St, Atlanta, GA 30301",sales6.csv,7
65754,236666,20in Monitor,1,109.989998,07/31/19 20:11,"866 14th St, San Francisco, CA 94016",sales6.csv,7
65755,236667,AAA Batteries (4-pack),1,2.990000,07/17/19 22:29,"249 Cherry St, Dallas, TX 75001",sales6.csv,7
65756,236668,Wired Headphones,1,11.990000,07/30/19 19:28,"727 Wilson St, Austin, TX 73301",sales6.csv,7
65757,236669,AAA Batteries (4-pack),1,2.990000,07/10/19 01:50,"743 9th St, New York City, NY 10001",sales6.csv,7

In [30]:
all_sales[['Product', 'Quantity Ordered', 'Price Each']]

                          Product  Quantity Ordered  Price Each
0                Wired Headphones                 2   11.990000
1      Bose SoundSport Headphones                 1   99.989998
2                          iPhone                 1  700.000000
3           AA Batteries (4-pack)                 2    3.840000
4           AA Batteries (4-pack)                 2    3.840000
...                           ...               ...         ...
65753            Wired Headphones                 1   11.990000
65754                20in Monitor                 1  109.989998
65755      AAA Batteries (4-pack)                 1    2.990000
65756            Wired Headphones                 1   11.990000
65757      AAA Batteries (4-pack)                 1    2.990000

[65758 rows x 3 columns]

In [31]:
all_sales['Sales'] = all_sales['Quantity Ordered'].astype(float) * all_sales['Price Each'].astype(float)
all_sales

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,source_file,Month,Sales
0,236670,Wired Headphones,2,11.990000,08/31/19 22:21,"359 Spruce St, Seattle, WA 98101",sales1.csv,8,23.980000
1,236671,Bose SoundSport Headphones,1,99.989998,08/15/19 15:11,"492 Ridge St, Dallas, TX 75001",sales1.csv,8,99.989998
2,236672,iPhone,1,700.000000,08/06/19 14:40,"149 7th St, Portland, OR 97035",sales1.csv,8,700.000000
3,236673,AA Batteries (4-pack),2,3.840000,08/29/19 20:59,"631 2nd St, Los Angeles, CA 90001",sales1.csv,8,7.680000
4,236674,AA Batteries (4-pack),2,3.840000,08/15/19 19:53,"736 14th St, New York City, NY 10001",sales1.csv,8,7.680000
...,...,...,...,...,...,...,...,...,...
65753,236665,Wired Headphones,1,11.990000,07/20/19 16:16,"694 Meadow St, Atlanta, GA 30301",sales6.csv,7,11.990000
65754,236666,20in Monitor,1,109.989998,07/31/19 20:11,"866 14th St, San Francisco, CA 94016",sales6.csv,7,109.989998
65755,236667,AAA Batteries (4-pack),1,2.990000,07/17/19 22:29,"249 Cherry St, Dallas, TX 75001",sales6.csv,7,2.990000
65756,236668,Wired Headphones,1,11.990000,07/30/19 19:28,"727 Wilson St, Austin, TX 73301",sales6.csv,7,11.990000
65757,236669,AAA Batteries (4-pack),1,2.990000,07/10/19 01:50,"743 9th St, New York City, NY 10001",sales6.csv,7,2.990000

In [32]:
all_sales['Sales'].min()

2.990000009536743

In [33]:
all_sales['Sales'].max()

1999.97998046875

In [34]:
all_sales['Sales'].sum()

12149198.909053564

In [35]:
all_sales[all_sales['Sales'] == all_sales['Sales'].max()]

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,source_file,Month,Sales
32959,149611,ThinkPad Laptop,2,999.98999,01/31/19 17:47,"850 6th St, New York City, NY 10001",sales4.csv,1,1999.97998

In [36]:
all_sales[all_sales['Sales'] == all_sales['Sales'].min()]

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,source_file,Month,Sales
16,236686,AAA Batteries (4-pack),1,2.99,08/15/19 19:13,"766 Maple St, Dallas, TX 75001",sales1.csv,8,2.99
19,236689,AAA Batteries (4-pack),1,2.99,08/21/19 10:55,"13 Cedar St, San Francisco, CA 94016",sales1.csv,8,2.99
20,236690,AAA Batteries (4-pack),1,2.99,08/08/19 12:00,"139 River St, San Francisco, CA 94016",sales1.csv,8,2.99
50,236719,AAA Batteries (4-pack),1,2.99,08/05/19 12:09,"948 2nd St, Atlanta, GA 30301",sales1.csv,8,2.99
64,236731,AAA Batteries (4-pack),1,2.99,08/29/19 12:40,"62 Center St, San Francisco, CA 94016",sales1.csv,8,2.99
...,...,...,...,...,...,...,...,...,...
65697,236612,AAA Batteries (4-pack),1,2.99,07/28/19 14:17,"882 2nd St, San Francisco, CA 94016",sales6.csv,7,2.99
65699,236614,AAA Batteries (4-pack),1,2.99,07/01/19 14:39,"332 12th St, Los Angeles, CA 90001",sales6.csv,7,2.99
65752,236664,AAA Batteries (4-pack),1,2.99,07/03/19 08:18,"301 12th St, San Francisco, CA 94016",sales6.csv,7,2.99
65755,236667,AAA Batteries (4-pack),1,2.99,07/17/19 22:29,"249 Cherry St, Dallas, TX 75001",sales6.csv,7,2.99
65757,236669,AAA Batteries (4-pack),1,2.99,07/10/19 01:50,"743 9th St, New York City, NY 10001",sales6.csv,7,2.99

In [37]:
sum_sales=all_sales.groupby('Month').sum()
sum_sales

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,source_file,Sales
Month,,,,,,,,
1,1411189528,iPhoneLightning Charging CableWired Headphones...,10862,1.803265e+06,01/22/19 21:2501/28/19 14:1501/17/19 13:3301/0...,"944 Walnut St, Boston, MA 02215185 Maple St, P...",sales4.csvsales4.csvsales4.csvsales4.csvsales4...,1.813586e+06
2,1871052592,iPhoneAA Batteries (4-pack)27in 4K Gaming Moni...,13449,2.188885e+06,02/18/19 01:3502/13/19 07:2402/18/19 09:4602/0...,"866 Spruce St, Portland, ME 0410118 13th St, S...",sales3.csvsales3.csvsales3.csvsales3.csvsales3...,2.202022e+06
3,2648245,AAA Batteries (4-pack)AAA Batteries (4-pack)Wi...,18,3.203660e+03,03/01/19 03:0603/01/19 01:0303/01/19 02:1803/0...,"270 Dogwood St, San Francisco, CA 94016683 Ada...",sales3.csvsales3.csvsales3.csvsales3.csvsales3...,3.207500e+03
7,3280236217,Apple Airpods HeadphonesFlatscreen TVAA Batter...,16051,2.629541e+06,07/26/19 16:5107/05/19 08:5507/29/19 12:4107/2...,"389 South St, Atlanta, GA 30301590 4th St, Sea...",sales6.csvsales6.csvsales6.csvsales6.csvsales6...,2.644747e+06
8,2899373917,Wired HeadphonesBose SoundSport HeadphonesiPho...,13448,2.230346e+06,08/31/19 22:2108/15/19 15:1108/06/19 14:4008/2...,"359 Spruce St, Seattle, WA 98101492 Ridge St, ...",sales1.csvsales1.csvsales1.csvsales1.csvsales1...,2.244468e+06
9,2917549,Apple Airpods Headphones34in Ultrawide Monitor...,12,2.096740e+03,09/01/19 04:1309/01/19 01:0909/01/19 02:0709/0...,"761 Forest St, San Francisco, CA 94016373 1st ...",sales1.csvsales1.csvsales1.csvsales1.csvsales1...,2.096740e+03
11,5041253625,Wired HeadphonesUSB-C Charging CableApple Airp...,19774,3.177105e+06,11/21/19 09:5411/17/19 10:0311/19/19 14:5611/2...,"46 Park St, New York City, NY 10001962 Hickory...",sales5.csvsales5.csvsales5.csvsales5.csvsales5...,3.196093e+06
12,86146045,Macbook Pro LaptopLG Washing MachineUSB-C Char...,330,4.278057e+04,12/30/19 00:0112/29/19 07:0312/12/19 18:2112/2...,"136 Church St, New York City, NY 10001562 2nd ...",sales2.csvsales2.csvsales2.csvsales2.csvsales2...,4.297789e+04

In [38]:
sum_sales = sum_sales.drop(['Order ID', 'Product', 'Order Date', 'Purchase Address', 'source_file'], axis=1)
sum_sales

       Quantity Ordered    Price Each         Sales
Month
1                 10862  1.803265e+06  1.813586e+06
2                 13449  2.188885e+06  2.202022e+06
3                    18  3.203660e+03  3.207500e+03
7                 16051  2.629541e+06  2.644747e+06
8                 13448  2.230346e+06  2.244468e+06
9                    12  2.096740e+03  2.096740e+03
11                19774  3.177105e+06  3.196093e+06
12                  330  4.278057e+04  4.297789e+04

In [39]:
sum_sales[sum_sales['Sales'] == sum_sales['Sales'].min()]

       Quantity Ordered  Price Each        Sales
Month
9                    12  2096.73999  2096.739981

In [40]:
sum_sales[sum_sales['Sales'] == sum_sales['Sales'].max()]

       Quantity Ordered  Price Each         Sales
Month
11                19774   3177105.0  3.196093e+06

In [41]:
all_sales

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,source_file,Month,Sales
0,236670,Wired Headphones,2,11.990000,08/31/19 22:21,"359 Spruce St, Seattle, WA 98101",sales1.csv,8,23.980000
1,236671,Bose SoundSport Headphones,1,99.989998,08/15/19 15:11,"492 Ridge St, Dallas, TX 75001",sales1.csv,8,99.989998
2,236672,iPhone,1,700.000000,08/06/19 14:40,"149 7th St, Portland, OR 97035",sales1.csv,8,700.000000
3,236673,AA Batteries (4-pack),2,3.840000,08/29/19 20:59,"631 2nd St, Los Angeles, CA 90001",sales1.csv,8,7.680000
4,236674,AA Batteries (4-pack),2,3.840000,08/15/19 19:53,"736 14th St, New York City, NY 10001",sales1.csv,8,7.680000
...,...,...,...,...,...,...,...,...,...
65753,236665,Wired Headphones,1,11.990000,07/20/19 16:16,"694 Meadow St, Atlanta, GA 30301",sales6.csv,7,11.990000
65754,236666,20in Monitor,1,109.989998,07/31/19 20:11,"866 14th St, San Francisco, CA 94016",sales6.csv,7,109.989998
65755,236667,AAA Batteries (4-pack),1,2.990000,07/17/19 22:29,"249 Cherry St, Dallas, TX 75001",sales6.csv,7,2.990000
65756,236668,Wired Headphones,1,11.990000,07/30/19 19:28,"727 Wilson St, Austin, TX 73301",sales6.csv,7,11.990000
65757,236669,AAA Batteries (4-pack),1,2.990000,07/10/19 01:50,"743 9th St, New York City, NY 10001",sales6.csv,7,2.990000

In [42]:
all_sales['Purchase Address']

0            359 Spruce St, Seattle, WA 98101
1              492 Ridge St, Dallas, TX 75001
2              149 7th St, Portland, OR 97035
3           631 2nd St, Los Angeles, CA 90001
4        736 14th St, New York City, NY 10001
                         ...
65753        694 Meadow St, Atlanta, GA 30301
65754    866 14th St, San Francisco, CA 94016
65755         249 Cherry St, Dallas, TX 75001
65756         727 Wilson St, Austin, TX 73301
65757     743 9th St, New York City, NY 10001
Name: Purchase Address, Length: 65758, dtype: object

In [43]:
all_sales['Purchase Address'].str[-8:]

0        WA 98101
1        TX 75001
2        OR 97035
3        CA 90001
4        NY 10001
           ...
65753    GA 30301
65754    CA 94016
65755    TX 75001
65756    TX 73301
65757    NY 10001
Name: Purchase Address, Length: 65758, dtype: object

In [44]:
all_sales['Purchase Address'].str[:-6]

0            359 Spruce St, Seattle, WA
1              492 Ridge St, Dallas, TX
2              149 7th St, Portland, OR
3           631 2nd St, Los Angeles, CA
4        736 14th St, New York City, NY
                      ...
65753        694 Meadow St, Atlanta, GA
65754    866 14th St, San Francisco, CA
65755         249 Cherry St, Dallas, TX
65756         727 Wilson St, Austin, TX
65757     743 9th St, New York City, NY
Name: Purchase Address, Length: 65758, dtype: object

In [45]:
all_sales

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,source_file,Month,Sales
0,236670,Wired Headphones,2,11.990000,08/31/19 22:21,"359 Spruce St, Seattle, WA 98101",sales1.csv,8,23.980000
1,236671,Bose SoundSport Headphones,1,99.989998,08/15/19 15:11,"492 Ridge St, Dallas, TX 75001",sales1.csv,8,99.989998
2,236672,iPhone,1,700.000000,08/06/19 14:40,"149 7th St, Portland, OR 97035",sales1.csv,8,700.000000
3,236673,AA Batteries (4-pack),2,3.840000,08/29/19 20:59,"631 2nd St, Los Angeles, CA 90001",sales1.csv,8,7.680000
4,236674,AA Batteries (4-pack),2,3.840000,08/15/19 19:53,"736 14th St, New York City, NY 10001",sales1.csv,8,7.680000
...,...,...,...,...,...,...,...,...,...
65753,236665,Wired Headphones,1,11.990000,07/20/19 16:16,"694 Meadow St, Atlanta, GA 30301",sales6.csv,7,11.990000
65754,236666,20in Monitor,1,109.989998,07/31/19 20:11,"866 14th St, San Francisco, CA 94016",sales6.csv,7,109.989998
65755,236667,AAA Batteries (4-pack),1,2.990000,07/17/19 22:29,"249 Cherry St, Dallas, TX 75001",sales6.csv,7,2.990000
65756,236668,Wired Headphones,1,11.990000,07/30/19 19:28,"727 Wilson St, Austin, TX 73301",sales6.csv,7,11.990000
65757,236669,AAA Batteries (4-pack),1,2.990000,07/10/19 01:50,"743 9th St, New York City, NY 10001",sales6.csv,7,2.990000

In [46]:
all_sales['Purchase Address'].str[-8:-6]

0        WA
1        TX
2        OR
3        CA
4        NY
         ..
65753    GA
65754    CA
65755    TX
65756    TX
65757    NY
Name: Purchase Address, Length: 65758, dtype: object

In [47]:
all_sales['State'] = all_sales['Purchase Address'].str[-8:-6]
all_sales

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,source_file,Month,Sales,State
0,236670,Wired Headphones,2,11.990000,08/31/19 22:21,"359 Spruce St, Seattle, WA 98101",sales1.csv,8,23.980000,WA
1,236671,Bose SoundSport Headphones,1,99.989998,08/15/19 15:11,"492 Ridge St, Dallas, TX 75001",sales1.csv,8,99.989998,TX
2,236672,iPhone,1,700.000000,08/06/19 14:40,"149 7th St, Portland, OR 97035",sales1.csv,8,700.000000,OR
3,236673,AA Batteries (4-pack),2,3.840000,08/29/19 20:59,"631 2nd St, Los Angeles, CA 90001",sales1.csv,8,7.680000,CA
4,236674,AA Batteries (4-pack),2,3.840000,08/15/19 19:53,"736 14th St, New York City, NY 10001",sales1.csv,8,7.680000,NY
...,...,...,...,...,...,...,...,...,...,...
65753,236665,Wired Headphones,1,11.990000,07/20/19 16:16,"694 Meadow St, Atlanta, GA 30301",sales6.csv,7,11.990000,GA
65754,236666,20in Monitor,1,109.989998,07/31/19 20:11,"866 14th St, San Francisco, CA 94016",sales6.csv,7,109.989998,CA
65755,236667,AAA Batteries (4-pack),1,2.990000,07/17/19 22:29,"249 Cherry St, Dallas, TX 75001",sales6.csv,7,2.990000,TX
65756,236668,Wired Headphones,1,11.990000,07/30/19 19:28,"727 Wilson St, Austin, TX 73301",sales6.csv,7,11.990000,TX
65757,236669,AAA Batteries (4-pack),1,2.990000,07/10/19 01:50,"743 9th St, New York City, NY 10001",sales6.csv,7,2.990000,NY

In [49]:
state_sales=all_sales.groupby('State').sum()
state_sales

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,source_file,Month,Sales
State,,,,,,,,,
CA,5843578956,AA Batteries (4-pack)Wired Headphones34in Ultr...,29633,4.785582e+06,08/29/19 20:5908/02/19 23:5408/04/19 19:5208/1...,"631 2nd St, Los Angeles, CA 90001470 Hill St, ...",sales1.csvsales1.csvsales1.csvsales1.csvsales1...,170525,4.814242e+06
GA,1166278877,Apple Airpods HeadphonesAA Batteries (4-pack)B...,5824,9.801718e+05,08/23/19 19:2908/20/19 21:0708/08/19 06:0908/3...,"238 Highland St, Atlanta, GA 30301763 Hill St,...",sales1.csvsales1.csvsales1.csvsales1.csvsales1...,34067,9.852326e+05
MA,1567130649,AA Batteries (4-pack)USB-C Charging CableAA Ba...,7956,1.295225e+06,08/26/19 20:5208/23/19 07:3408/30/19 07:1408/2...,"295 1st St, Boston, MA 02215916 Meadow St, Bos...",sales1.csvsales1.csvsales1.csvsales1.csvsales1...,45849,1.302871e+06
ME,198275085,ThinkPad Laptop27in 4K Gaming Monitor27in FHD ...,1008,1.546342e+05,08/10/19 11:2108/03/19 09:1808/28/19 17:5508/1...,"526 North St, Portland, ME 04101534 Washington...",sales1.csvsales1.csvsales1.csvsales1.csvsales1...,5757,1.556802e+05
NY,1969177241,AA Batteries (4-pack)Lightning Charging CableU...,9972,1.648603e+06,08/15/19 19:5308/09/19 16:5008/23/19 12:5408/1...,"736 14th St, New York City, NY 10001669 12th S...",sales1.csvsales1.csvsales1.csvsales1.csvsales1...,57461,1.660474e+06
OR,771120908,iPhoneAA Batteries (4-pack)27in 4K Gaming Moni...,3908,6.423722e+05,08/06/19 14:4008/19/19 12:4008/12/19 21:5708/2...,"149 7th St, Portland, OR 97035118 Johnson St, ...",sales1.csvsales1.csvsales1.csvsales1.csvsales1...,22488,6.459790e+05
TX,1916273278,Bose SoundSport Headphones27in FHD MonitorAAA ...,9760,1.609986e+06,08/15/19 15:1108/31/19 15:4708/15/19 19:1308/0...,"492 Ridge St, Dallas, TX 75001196 West St, Dal...",sales1.csvsales1.csvsales1.csvsales1.csvsales1...,55575,1.618101e+06
WA,1162982724,Wired HeadphonesApple Airpods HeadphonesLightn...,5883,9.606485e+05,08/31/19 22:2108/02/19 12:2408/13/19 10:2908/0...,"359 Spruce St, Seattle, WA 98101198 Highland S...",sales1.csvsales1.csvsales1.csvsales1.csvsales1...,34240,9.666199e+05

In [52]:
state_sales = state_sales.drop(['Order ID', 'Product', 'Quantity Ordered', 'Price Each','Order Date','Purchase Address','Month','source_file'], axis=1)
state_sales

              Sales
State
CA     4.814242e+06
GA     9.852326e+05
MA     1.302871e+06
ME     1.556802e+05
NY     1.660474e+06
OR     6.459790e+05
TX     1.618101e+06
WA     9.666199e+05

In [55]:
state_sales[state_sales['Sales'] == state_sales['Sales'].max()]

              Sales
State
CA     4.814242e+06